export default function robots() {
  const baseUrl = process.env.NEXTAUTH_URL || "https://mellycrochets.shop";
  return {
    rules: {
      userAgent: "*",
      allow: [
        "/",
        "/shop",
        "/crochets",
        "/crochets/*",
        "/crochet_designs",
        "/crochet_designs/*",
        "/blog",
        "/blog_posts",
        "/blog_posts/*",
        "/categories",
        "/categories/*",
        "/tags",
        "/tags/*",
        "/about",
        "/contact",
        "/privacy-policy",
        "/cart",
        "/feed.xml",
        "/rss.xml",
      ],
      disallow: [
        "/dashboard/*",
        "/api/*",
        "/admin/*",
        "/checkout/*",
        "/account/*",
        "/profile",
        "/orders",
        "/orders/*",
        "/payment-success",
        "/private-*",
        "/404",
      ],
      crawlDelay: 10,
      cleanParam: "ref,utm_source,utm_medium,utm_campaign,sessionid",
    },
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}